
# Un make simple para limpiar los archivos .pyc y para generar la documentación
# del proyecto 3


docs : 
	doxygen Doxyfile
	
clean_docs:
	rm -rf docs

.PHONY : clean 

clean :
	rm ./src/cifrado/*.pyc